apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: tpswe294f-python
  janus-idp.io/tekton: tpswe294f-python
  backstage.io/kubernetes-id: tpswe294f-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tpswe294f-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
